coverage:
  status:
    project:
      default:
        threshold: 40%
      #   flags:
      #     - botonic-plugin-contentful
      #     - botonic-react
      #     - botonic-core
      #     - botonic-plugin-dynamodb
      # botonic-plugin-contentful:
      #   flags:
      #     - botonic-plugin-contentful
      # botonic-react:
      #   flags:
      #     - botonic-react
      # botonic-core:
      #   flags:
      #     - botonic-core
      # botonic-plugin-dynamodb:
      #   flags:
      #     - botonic-plugin-dynamodb
      
        
        
        # if the coverage is under this value the Codecov GitHub check will fail
        #
flags:
  botonic-plugin-contentful:
    paths:
      - packages/botonic-plugin-contentful
    carryforward: true
  botonic-react:
    paths:
      - packages/botonic-react
    carryforward: true
  botonic-core:
    paths:
      - packages/botonic-core
    carryforward: true
  botonic-plugin-dynamodb:
    paths:
      - packages/botonic-plugin-dynamodb
    carryforward: true
